# Generated by Django 4.2.4 on 2023-08-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_following_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reg_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
