# Generated by Django 4.2.4 on 2023-08-31 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_post_image_or_video_remove_profile_reg_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.department'),
        ),
    ]
