# Generated by Django 4.2.4 on 2023-09-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_profile_city_profile_state_alter_following_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
