# Generated by Django 4.2.4 on 2023-09-07 10:51

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('services', '0008_alter_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interesttag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='interesttag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='skilltag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='skilltag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='HashTag',
        ),
        migrations.DeleteModel(
            name='InterestTag',
        ),
        migrations.DeleteModel(
            name='SkillTag',
        ),
    ]
